server:
  port: 8080

spring:
  application:
    name: Pharmacy Fair Dev

  output:
    ansi:
      enabled: detect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pharmacy
    username: postgres
    password: postgres
    hikari:
      schema: public

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        format_sql: true

  flyway:
    driver-class-name: org.postgresql.Driver
    validate-on-migrate: true
    enabled: true

  docker:
    compose:
      enabled: true
      file: classpath:docker/docker-compose.yaml

logging:
  level:
    gamz:
      projects.*: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread]: %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.sss} [%thread] %-5level %logger{36}: %msg%n"
  file:
    name: logs/dev/application.log
    path: logs/dev

management:
  endpoints:
    web:
      exposure:
        include: '*'