spring:
  application:
    name: Pharmacy Fair
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/pharmacy
    username: postgres
    password: postgres

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers
  endpoint:
    health:
      show-details: always