services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no

volumes:
  postgres_data: