services:
  postgres:
    # always если нужно сохранять данные
    # no во время разработки, стирался и создавался заново
    restart: no
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy