INSERT INTO medication_forms (form_code, form_name, parent_id, level)
VALUES
    ('1', 'Аэрозоль', NULL, 1),
    ('1.1', 'Аэрозоль для ингаляций дозированный', (SELECT id FROM medication_forms WHERE code = '1'), 2),
    ('1.2', 'Аэрозоль для местного применения', (SELECT id FROM medication_forms WHERE code = '1'), 2),
    ('1.3', 'Аэрозоль для нанесения на слизистую оболочку полости рта', (SELECT id FROM medication_forms WHERE code = '1'), 2),
    ('1.4', 'Аэрозоль для наружного применения', (SELECT id FROM medication_forms WHERE code = '1'), 2),
    ('1.5', 'Аэрозоль назальный', (SELECT id FROM medication_forms WHERE code = '1'), 2),
    ('1.6', 'Аэрозоль подъязычный', (SELECT id FROM medication_forms WHERE code = '1'), 2),
    ('1.7', 'Аэрозоль трансдермальный', (SELECT id FROM medication_forms WHERE code = '1'), 2),
    ('1.8', 'Аэрозоль ушной', (SELECT id FROM medication_forms WHERE code = '1'), 2),

    ('2', 'Газ медицинский', NULL, 1),
    ('2.1', 'Газ медицинский криогенный', (SELECT id FROM medication_forms WHERE code = '2'), 2),
    ('2.2', 'Газ медицинский сжатый', (SELECT id FROM medication_forms WHERE code = '2'), 2),
    ('2.3', 'Газ медицинский сжиженный', (SELECT id FROM medication_forms WHERE code = '2'), 2),

    ('3', 'Гель', NULL, 1),
    ('3.1', 'Гель вагинальный', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.2', 'Гель глазной', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.3', 'Гель для инъекций', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.4', 'Гель для местного применения', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.5', 'Гель для нанесения на десны', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.6', 'Гель для нанесения на слизистую оболочку полости рта', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.7', 'Гель для наружного применения', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.8', 'Гель для подкожного введения', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.9', 'Гель для приготовления суспензии для приема внутрь', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.10', 'Гель для приема внутрь', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.11', 'Гель зубной', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.12', 'Гель интестинальный', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.13', 'Гель назальный', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.14', 'Гель периодонтальный', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.15', 'Гель ректальный', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.16', 'Гель стоматологический', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.17', 'Гель трансдермальный', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.18', 'Гель уретральный', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.19', 'Гель ушной', (SELECT id FROM medication_forms WHERE code = '3'), 2),
    ('3.20', 'Гель эндоцервикальный', (SELECT id FROM medication_forms WHERE code = '3'), 2),

    ('4', 'Гранулы', NULL, 1),
    ('4.1', 'Гранулы', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.2', 'Гранулы для приготовления...', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.2.1', '<...> капель', (SELECT id FROM medication_forms WHERE code = '4.2'), 3),
    ('4.2.2', '<...> раствора', (SELECT id FROM medication_forms WHERE code = '4.2'), 3),
    ('4.2.3', '<...> сиропа', (SELECT id FROM medication_forms WHERE code = '4.2'), 3),
    ('4.2.4', '<...> суспензии', (SELECT id FROM medication_forms WHERE code = '4.2'), 3),
    ('4.3', 'Гранулы для рассасывания', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.4', 'Гранулы кишечнорастворимые', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.5', 'Гранулы кишечнорастворимые с пролонгированным высвобождением', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.6', 'Гранулы, покрытые оболочкой', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.7', 'Гранулы резано-прессованные', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.8', 'Гранулы с модифицированным высвобождением', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.9', 'Гранулы с пролонгированным высвобождением', (SELECT id FROM medication_forms WHERE code = '4'), 2),
    ('4.10', 'Гранулы шипучие', (SELECT id FROM medication_forms WHERE code = '4'), 2),

    ('5', 'Дисперсия', NULL, 1),
    ('5.1', 'Дисперсия для внутривенного введения', (SELECT id FROM medication_forms WHERE code = '5'), 2),
    ('5.2', 'Дисперсия для внутрикожного введения', (SELECT id FROM medication_forms WHERE code = '5'), 2),
    ('5.3', 'Дисперсия для инфузий', (SELECT id FROM medication_forms WHERE code = '5'), 2),
    ('5.4', 'Дисперсия для инъекций', (SELECT id FROM medication_forms WHERE code = '5'), 2),

    ('6', 'Жидкость', NULL, 1),
    ('6.1', 'Жидкость для ингаляций', (SELECT id FROM medication_forms WHERE code = '6'), 2),
    ('6.2', 'Жидкость для наружного применения', (SELECT id FROM medication_forms WHERE code = '6'), 2),
    ('6.3', 'Жидкость для приема внутрь', (SELECT id FROM medication_forms WHERE code = '6'), 2),

    ('7', 'Имплантат', NULL, 1),
    ('7.1', 'Имплантат', (SELECT id FROM medication_forms WHERE code = '7'), 2),
    ('7.2', 'Имплантат интравитреальный', (SELECT id FROM medication_forms WHERE code = '7'), 2),

    ('8', 'Капли', NULL, 1),
    ('8.1', 'Капли глазные', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.2', 'Капли глазные с пролонгированным высвобождением', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.3', 'Капли для ингаляций', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.4', 'Капли для местного применения', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.5', 'Капли для нанесения на слизистую оболочку полости рта', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.6', 'Капли для приема внутрь', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.7', 'Капли зубные', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.8', 'Капли назальные', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.9', 'Капли подъязычные', (SELECT id FROM medication_forms WHERE code = '8'), 2),
    ('8.10', 'Капли ушные', (SELECT id FROM medication_forms WHERE code = '8'), 2),

    ('9', 'Капсулы', NULL, 1),
    ('9.1', 'Капсулы', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.2', 'Капсулы вагинальные', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.3', 'Капсулы внутриматочные', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.4', 'Капсулы жевательные', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.5', 'Капсулы кишечнорастворимые', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.6', 'Капсулы кишечнорастворимые с пролонгированным высвобождением', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.7', 'Капсулы подъязычные', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.8', 'Капсулы ректальные', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.9', 'Капсулы с модифицированным высвобождением', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.10', 'Капсулы с порошком для ингаляций', (SELECT id FROM medication_forms WHERE code = '9'), 2),
    ('9.11', 'Капсулы с пролонгированным высвобождением', (SELECT id FROM medication_forms WHERE code = '9'), 2),

    ('10', 'Концентрат', NULL, 1),
    ('10.1', 'Концентрат для приготовления...', (SELECT id FROM medication_forms WHERE code = '10'), 2),
    ('10.1.1', '<...> дисперсии...', (SELECT id FROM medication_forms WHERE code = '10.1'), 3),
    ('10.1.2', '<...> раствора...', (SELECT id FROM medication_forms WHERE code = '10.1'), 3),
    ('10.1.3', '<...> суспензии...', (SELECT id FROM medication_forms WHERE code = '10.1'), 3),
    ('10.1.4', '<...> эмульсии...', (SELECT id FROM medication_forms WHERE code = '10.1'), 3),

    ('11', 'Крем', NULL, 1),
    ('11.1', 'Крем вагинальный', (SELECT id FROM medication_forms WHERE code = '11'), 2),
    ('11.2', 'Крем глазной', (SELECT id FROM medication_forms WHERE code = '11'), 2),
    ('11.3', 'Крем для местного применения', (SELECT id FROM medication_forms WHERE code = '11'), 2),
    ('11.4', 'Крем для нанесения на слизистую оболочку полости рта', (SELECT id FROM medication_forms WHERE code = '11'), 2),
    ('11.5', 'Крем для наружного применения', (SELECT id FROM medication_forms WHERE code = '11'), 2),
    ('11.6', 'Крем назальный', (SELECT id FROM medication_forms WHERE code = '11'), 2),
    ('11.7', 'Крем ректальный', (SELECT id FROM medication_forms WHERE code = '11'), 2),
    ('11.8', 'Крем ушной', (SELECT id FROM medication_forms WHERE code = '11'), 2),

    ('12', 'Линимент', NULL, 1),
    ('12.1', 'Линимент вагинальный', (SELECT id FROM medication_forms WHERE code = '12'), 2),
    ('12.2', 'Линимент для местного применения', (SELECT id FROM medication_forms WHERE code = '12'), 2),
    ('12.3', 'Линимент для наружного применения', (SELECT id FROM medication_forms WHERE code = '12'), 2),
    ('12.4', 'Линимент периодонтальный', (SELECT id FROM medication_forms WHERE code = '12'), 2),
    ('12.5', 'Линимент эндоцервикальный', (SELECT id FROM medication_forms WHERE code = '12'), 2),

    ('13', 'Лиофилизат', NULL, 1),
    ('13.1', 'Лиофилизат для приготовления...', (SELECT id FROM medication_forms WHERE code = '13'), 2),
    ('13.1.1', '<...> дисперсии...', (SELECT id FROM medication_forms WHERE code = '13.1'), 3),
    ('13.1.2', '<...> капель...', (SELECT id FROM medication_forms WHERE code = '13.1'), 3),
    ('13.1.3', '<...> концентрата...', (SELECT id FROM medication_forms WHERE code = '13.1'), 3),
    ('13.1.4', '<...> раствора...', (SELECT id FROM medication_forms WHERE code = '13.1'), 3),
    ('13.1.5', '<...> спрея...', (SELECT id FROM medication_forms WHERE code = '13.1'), 3),
    ('13.1.6', '<...> суспензии...', (SELECT id FROM medication_forms WHERE code = '13.1'), 3),
    ('13.1.7', '<...> эмульсии...', (SELECT id FROM medication_forms WHERE code = '13.1'), 3),

    ('14', 'Мазь', NULL, 1),
    ('14.1', 'Мазь вагинальная', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.2', 'Мазь глазная', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.3', 'Мазь для ингаляций', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.4', 'Мазь для местного применения', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.5', 'Мазь для нанесения на слизистую оболочку полости рта', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.6', 'Мазь для наружного применения', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.7', 'Мазь назальная', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.8', 'Мазь ректальная', (SELECT id FROM medication_forms WHERE code = '14'), 2),
    ('14.9', 'Мазь ушная', (SELECT id FROM medication_forms WHERE code = '14'), 2),

    ('15', 'Масло', NULL, 1),
    ('15.1', 'Масло для ингаляций', (SELECT id FROM medication_forms WHERE code = '15'), 2),
    ('15.2', 'Масло для местного применения', (SELECT id FROM medication_forms WHERE code = '15'), 2),
    ('15.3', 'Масло для наружного применения', (SELECT id FROM medication_forms WHERE code = '15'), 2),
    ('15.4', 'Масло для приема внутрь', (SELECT id FROM medication_forms WHERE code = '15'), 2),

    ('16', 'Настойка', NULL, 1),
    ('16.1', 'Настойка', (SELECT id FROM medication_forms WHERE code = '16'), 2),
    ('16.2', 'Настойка для ингаляций', (SELECT id FROM medication_forms WHERE code = '16'), 2),
    ('16.3', 'Настойка для местного применения', (SELECT id FROM medication_forms WHERE code = '16'), 2),
    ('16.4', 'Настойка для наружного применения', (SELECT id FROM medication_forms WHERE code = '16'), 2),

    ('17', 'Палочки', NULL, 1),
    ('17.1', 'Палочки дентальные', (SELECT id FROM medication_forms WHERE code = '17'), 2),
    ('17.2', 'Палочки назальные', (SELECT id FROM medication_forms WHERE code = '17'), 2),
    ('17.3', 'Палочки периодонтальные', (SELECT id FROM medication_forms WHERE code = '17'), 2),
    ('17.4', 'Палочки уретральные', (SELECT id FROM medication_forms WHERE code = '17'), 2),
    ('17.5', 'Палочки ушные', (SELECT id FROM medication_forms WHERE code = '17'), 2),

    ('18', 'Паста', NULL, 1),
    ('18.1', 'Паста для нанесения на десны', (SELECT id FROM medication_forms WHERE code = '18'), 2),
    ('18.2', 'Паста для нанесения на слизистую оболочку полости рта', (SELECT id FROM medication_forms WHERE code = '18'), 2),
    ('18.3', 'Паста для наружного применения', (SELECT id FROM medication_forms WHERE code = '18'), 2),
    ('18.4', 'Паста для приготовления суспензии для приема внутрь', (SELECT id FROM medication_forms WHERE code = '18'), 2),
    ('18.5', 'Паста для приема внутрь', (SELECT id FROM medication_forms WHERE code = '18'), 2),
    ('18.6', 'Паста лекарственная стоматологическая', (SELECT id FROM medication_forms WHERE code = '18'), 2),

    ('19', 'Пена лекарственная', NULL, 1),
    ('19.1', 'Пена вагинальная', (SELECT id FROM medication_forms WHERE code = '19'), 2),
    ('19.2', 'Пена внутриматочная', (SELECT id FROM medication_forms WHERE code = '19'), 2),
    ('19.3', 'Пена для наружного применения', (SELECT id FROM medication_forms WHERE code = '19'), 2),
    ('19.4', 'Пена ректальная', (SELECT id FROM medication_forms WHERE code = '19'), 2),

    ('20', 'Пластырь лекарственный', NULL, 1),
    ('20.1', 'Пластырь', (SELECT id FROM medication_forms WHERE code = '20'), 2),
    ('20.2', 'Пластырь для слизистой оболочки полости рта', (SELECT id FROM medication_forms WHERE code = '20'), 2),
    ('20(1)', 'Пластырь трансдермальный', (SELECT id FROM medication_forms WHERE code = '20'), 2),

    ('21', 'Пленки', NULL, 1),
    ('21.1', 'Пленки глазные', (SELECT id FROM medication_forms WHERE code = '21'), 2),
    ('21.2', 'Пленки, диспергируемые в полости рта', (SELECT id FROM medication_forms WHERE code = '21'), 2),
    ('21.3', 'Пленки для наклеивания на десну', (SELECT id FROM medication_forms WHERE code = '21'), 2),
    ('21.4', 'Пленки защечные', (SELECT id FROM medication_forms WHERE code = '21'), 2),
    ('21.5', 'Пленки периодонтальные', (SELECT id FROM medication_forms WHERE code = '21'), 2),
    ('21.6', 'Пленки подъязычные', (SELECT id FROM medication_forms WHERE code = '21'), 2),

    ('22', 'Порошок', NULL, 1),
    ('22.1', 'Порошок для ингаляций дозированный', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.2', 'Порошок для местного применения', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.3', 'Порошок для наружного применения', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.4', 'Порошок для приготовления...', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.4.1', '<...> геля...', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.4.2', '<...> дисперсии...', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.4.3', '<...> капель...', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.4.4', '<...> раствора...', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.4.5', '<...> пасты...', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.4.6', '<...> сиропа', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.4.7', '<...> спрея...', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.4.8', '<...> суспензии...', (SELECT id FROM medication_forms WHERE code = '22.4'), 3),
    ('22.5', 'Порошок для приема внутрь', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.6', 'Порошок назальный', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.7', 'Порошок периодонтальный', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.8', 'Порошок ушной', (SELECT id FROM medication_forms WHERE code = '22'), 2),
    ('22.9', 'Порошок шипучий', (SELECT id FROM medication_forms WHERE code = '22'), 2),

    ('23', 'Раствор', NULL, 1),
    ('23.1', 'Раствор вагинальный', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.2', 'Раствор внутриматочный', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.3', 'Раствор для внутриартериального введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.4', 'Раствор для внутрибрюшинного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.5', 'Раствор для внутривенного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.6', 'Раствор для внутриглазного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.7', 'Раствор для внутрикожного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.8', 'Раствор для внутрикоронарного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.9', 'Раствор для внутримышечного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.10', 'Раствор для внутриполостного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.11', 'Раствор для внутрипузырного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.12', 'Раствор для внутрисуставного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.13', 'Раствор для гастроэнтерального введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.14', 'Раствор для гемодиализа', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.15', 'Раствор для гемодиафильтрации', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.16', 'Раствор для гемофильтрации', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.17', 'Раствор для ингаляций', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.18', 'Раствор для интраамниального введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.19', 'Раствор для интралимфатического введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.20', 'Раствор для интратекального введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.21', 'Раствор для инфузий', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.22', 'Раствор для инъекций', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.23', 'Раствор для местного применения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.24', 'Раствор для накожного скарификационного нанесения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.25', 'Раствор для нанесения на десны', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.26', 'Раствор для наружного применения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.27', 'Раствор для околосуставного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.28', 'Раствор для орошения желудка', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.29', 'Раствор для орошения мочевого пузыря', (SELECT id FROM medication_forms WHERE code = '23'), 2),
    ('23.30', 'Раствор для парабульбарного введения', (SELECT id FROM medication_forms WHERE code = '23'), 2);

INSERT INTO priority_types (priority_code, priority_name, description)
VALUES
    ('MORT', 'Снижение смертности', 'Лекарства и медизделия, направленные на снижение смертности.'),
    ('DISAB', 'Снижение инвалидизации', 'Лекарства и медизделия, направленные на снижение уровня инвалидизации.'),
    ('TEMP_DIS', 'Снижение сроков временной нетрудоспособности', 'Лекарства и медизделия, направленные на сокращение времени, необходимого для восстановления трудоспособности.'),
    ('QL', 'Увеличение качества жизни, связанное с состоянием здоровья', 'Лекарства и медизделия, направленные на улучшение качества жизни пациентов.'),
    ('ORPHAN', 'Орфанные заболевания', 'Лекарства и медизделия для лечения редких (орфанных) заболеваний.'),
    ('TECH', 'Технологические тренды', 'Инновационные лекарства и медизделия, соответствующие современным технологическим трендам в медицине.'),
    ('IMPORT', 'Импортозамещение', 'Лекарства и медизделия, предназначенные для замещения импортных аналогов.'),
    ('MARKET', 'Рыночное превосходство (коммерческая перспективность)', 'Лекарства и медизделия с высоким потенциалом коммерческого успеха.');